Sonoma Web Apps support. Lit 3
khmyznikov/pwa-install pull request #37
Opened 2024-01-08 19:20 UTC by khmyznikov

Major release:
- PWA Install dialog for Sonoma Safari (need to test first)
- Upgrade to Lit v3
- New translation strings AI translated (need to verify)
- New Hide Screenshots property
- iOS start_url hack

2024-01-08 19:24 UTC, khmyznikov commented
Calling everyone who contributed to features and translations. Can you verify your language strings?
And also, if someone have Sonoma device, can you check in Safari? I will do this soon but it's not very handy for me.
@ShoWerZen @dartess @Blankjr @s0xDk @jivanf @MertcanDinler @hoRacy @benfavre @Georgegipa

2024-01-08 19:27 UTC, s0xDk commented
`uk` and `ru` looks fine.

will check Safari in Sonoma now...

2024-01-08 19:31 UTC, s0xDk commented
Works like a charm in Sonoma/Safari! 🔥

2024-01-08 20:26 UTC, jivanf commented
I can't test on Sonoma, but `es` LGTM

Thank you for this release!

2024-01-08 20:46 UTC, MertcanDinler requested changes

2024-01-08 20:46 UTC, MertcanDinler commented on i18n/tr.xlf
> +        <target>Geniş bir deneyim ve kolay erişim için Dock’a ekleyin.</target>
```suggestion
        <target>Daha iyi bir deneyim ve kolay erişim için Dock’a ekleyin.</target>
```

2024-01-08 20:46 UTC, MertcanDinler commented on i18n/tr.xlf
> +        <target>Geniş bir deneyim ve kolay erişim için Ana Ekranınıza ekleyin.</target>
```suggestion
        <target>Daha iyi bir deneyim ve kolay erişim için Ana Ekranınıza ekleyin.</target>
```

2024-01-08 20:46 UTC, MertcanDinler commented on i18n/tr.xlf
> +        <target>2) Dock’a Ekle’ye basın</target>
```suggestion
        <target>2) Dock’a ekleye basın</target>
```

2024-01-08 20:46 UTC, MertcanDinler commented on i18n/tr.xlf
> +        <target>Cihazınıza yükleyin, böylece geniş bir deneyim ve kolay erişime sahip olursunuz.</target>
```suggestion
        <target>Daha iyi bir deneyim ve kolay erişim için cihazınıza yükleyin.</target>
```

2024-01-10 07:55 UTC, hoRacy commented
PL looks fine. Thank for your work!

2024-01-10 21:34 UTC, Blankjr commented
DE string translations looking fine.  Appreciate your efforts!

2024-01-11 10:11 UTC, merged